### ISSUE TITLE
Bug: SPM configuration issue with ExampleTest.swift

### ISSUE THREAD

**Issue by jendaz** [MobileWalletProtocol/wallet-mobile-sdk#131]
### Describe the bug

I'm getting 'CoinbaseWalletSDK' is only available in iOS 13.0 or newer error in ExampleTest

### Steps

I just added the swift package to Test App with the target set to 15.5. and I'm getting that error in ExampleTest file. Maybe it is related to the package setting where I can see `platforms: [.iOS(.v12)]`

### Expected behavior

I'm expecting just build the app with the library.

### Version

1.0.3

**Comment by bangtoven** [comment]
hi @jendaz 
that's strange.
`ExampleTest` shouldn't be added to any app targets. 🤔 
have you run `pod install` on `example` folder? the example apps are set up with cocoapods, not SPM.

**Comment by jendaz** [comment]
Hi @bangtoven.

I just created an empty TestApp project and wanted to add this SDK using SPM by adding the package from this repo.
Then I tried to implement the setup part and the build of my project failed with that error.

When I tried to import the SDK using cocoapods, it worked as expected. But I'd like to use SPM instead.

**Comment by bangtoven** [comment]
hi @jendaz 
sounds like we have some issue on the SPM configuration. will address it soon and get back to you.
thanks for reporting. :)

**Comment by bangtoven** [comment]
@jendaz can you try again and let us know how it goes?

**Comment by jendaz** [comment]
@bangtoven It looks like it builds OK.

BTW I've noticed that the interface has changed on the master since version 1.0.4 that I can get from pods or SPM as exact version 1.0.4. What is this version's number? And when will it be released? It looks like it supports the app name and icon and that is exactly what I need.

**Comment by jendaz** [comment]
BTW #2:
With SPM I'm getting also android, flutter, docs sources that are not needed.

**Comment by bangtoven** [comment]
hey @jendaz 
1. we bump the version number when we deploy a new one. most up-to-date version out there is 1.0.4 as you saw. the master has some new changes that haven't been released yet.
as long as your app is available on app store, cbwallet app should be able to load the metadata like app name and icon using the packageId provided. 
we are making changes to allow client apps to pass the metadata in the future. we expect mid-december to apply changes to cbwallet app.

2. those files won't be added to build target. if you know a way to avoid cloning those, please let us know or feel free to open up a PR. :)
it seems like a known issue. https://github.com/apple/swift-package-manager/issues/4460#issuecomment-1116962025 not sure if there was any updates on this.
