### ISSUE TITLE
Bug: Android example app does not trigger connection request in Coinbase Wallet

### ISSUE THREAD

**Issue by ushafqat** [MobileWalletProtocol/wallet-mobile-sdk#162]
### Describe the bug

No message signing request is displayed in Coinbase Wallet

### Steps

1. Execute latest version of example app (commit #159) using Android Studio.
2. Click "Connect Wallet"
3. Select "Coinbase Wallet"
4. Navigates to Coinbase Wallet app

### Expected behavior

Show a message signing request to proceed with the handshake

### Version

1.0.4 / commit #159

### Additional info

The same flow on the example app was working for me before the holidays. Seems like the last update on Coinbase Wallet app was on Dec 25.

I have already tried reinstalling Coinbase Wallet, restarting Pixel, restarting Android Studio.

### Smartphone

Device: Pixel 6 Pro
OS: Android 13

**Comment by ushafqat** [comment]
Coinbase Wallet App version: 28.20.14

**Comment by AMITGOELNY** [comment]
Hi @ushafqat ,  the current Coinbase Wallet Mobile SDK may not work correctly with the current Coinbase Wallet Application.  The team is working on fixing this issue.  I'd suggest checking out an older commit of our SDK, and that should work accordingly.  We plan to have the latest demo app compatible with coiinbase wallet app in the coming weeks.

**Comment by ushafqat** [comment]
Thanks for the prompt reply @AMITGOELNY ! Any pointers on which commit should work fine? I was using #144 earlier which did seem to work through December but also stopped working in January.

**Comment by ushafqat** [comment]
I've tried commits back to #123 (which seems like the version update to 1.0.4) and still no signing message on Coinbase Wallet app.

**Comment by AMITGOELNY** [comment]
Hi @ushafqat there's an issue with our current coinbase wallet app as well.  Please retest once the wallet app is updated.

**Comment by vishnumad** [comment]
Version 28.20.17 of the CB Wallet app which was rolled out today should fix this issue. I'm closing the issue for now, let me know if the issue persists. Thank you!

**Comment by dpatel2161** [comment]
@vishnumad @AMITGOELNY - is this issue being looked into for iOS as well? I recently started running into it on iOS (RN integration) on the latest Coinbase Wallet App Store version (28.20.13)

Update: on iOS, 28.20.17 shows the wallet connect dialog. But on the sign message verification, the app crashes.

**Comment by vishnumad** [comment]
@dpatel2161 could you create a new issue in this repo for the app crash along with instructions on how to reproduce the crash? It seems unrelated to this existing issue.
