### ISSUE TITLE
Bug: CoinbaseWalletSDK/CoinbaseWalletSDK.swift:32: Fatal error: `CoinbaseWalletSDK.configure` should be called only once.

### ISSUE THREAD

**Issue by moesaid** [MobileWalletProtocol/wallet-mobile-sdk#173]
### Describe the bug

app crashes on second attempt to run configuration 

### Steps

1. configure once behave as it supposed to be 
2. on a second configuration return platform fatal error and crash the app

### Expected behavior

- away to check if already configured

### Version

1.0.4

### Additional info

```
flutter: <asynchronous suspension>
2
CoinbaseWalletSDK/CoinbaseWalletSDK.swift:32: Fatal error: `CoinbaseWalletSDK.configure` should be called only once.
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: `CoinbaseWalletSDK.configure` should be called only once.
    frame #0: 0x00000001875e00f8 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x1875e00f8 <+0>: ret
libswiftCore.dylib`:
    0x1875e00fc <+0>: b      0x1875e00f8               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x1875e0100 <+0>: adrp   x8, 366305
    0x1875e0104 <+4>: ldrb   w0, [x8, #0xabc]
Target 0: (Runner) stopped.
Lost connection to device.
```

**Comment by vishnumad** [comment]
This is expected behavior, you should only call the configure function once. If called multiple times, we throw an error on debug builds. Release builds should be unaffected.

**Comment by moesaid** [comment]
@vishnumad  thanks for letting me know. I am curious to understand the reasoning behind the chosen approach. 

Is there a way to verify whether the configuration has been invoked or a connection has been established prior to attempting to establish a new one? I apologize for requesting your expertise as I am relatively new to the SDK and have only recently begun exploring its features.

**Comment by bangtoven** [comment]
hey @moesaid 
for now, cbw sdk assumes that configuration doesn't change after it's set. it defines which wallet host your app will connect to and the callback url your app will get responses.
we do provide a way to check whether the sdk is configured: https://github.com/coinbase/wallet-mobile-sdk/blob/4ff27b7b7559f8a46549b69573c8aa3493344565/ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift#L23
give the log you shared, it seems you are using flutter. and probably our dart library might not be exposing this variable yet. please take a look at the flutter example code.

btw, our team is working on multi-wallet support and it will ease the restriction a bit. we expect to release the new sdk end of this quarter.

**Comment by moesaid** [comment]
@bangtoven Thank you for your prompt response. I appreciate it. I am eagerly anticipating the exposure of this flag and the future updates to the CBW SDK.

**Comment by bangtoven** [comment]
my pleasure! are you interested in trying out beta version of our sdk btw? it's not ready yet (https://github.com/coinbase/wallet-mobile-sdk/pull/146), but we could share some early version once it's in good shape and get your feedback.

**Comment by moesaid** [comment]
absolutely! i will take a spin latter today, hopefully play with it over the week!

**Comment by bangtoven** [comment]
@moesaid please try the new flutter lib v1.0.5.
it returns flutter exception instead of fatal error.
https://github.com/coinbase/wallet-mobile-sdk/pull/174/files

as i shared above, a long-term solution that we've been working on would be out soon.
