### ISSUE TITLE
Flutter Bug: optional parameters are required

### ISSUE THREAD

**Issue by moesaid** [MobileWalletProtocol/wallet-mobile-sdk#182]
### Describe the bug

optional parameters are required

### Steps

most of the exposed function have option and required prams but the optional prams still to be required, which defeats the purpose of having the optionality.

e.g

``` dart
 SendTransaction SendTransaction({
  required String fromAddress,
  required String? toAddress,
  required BigInt weiValue,
  required String data,
  required int? nonce,
  required BigInt? gasPriceInWei,
  required BigInt? maxFeePerGas,
  required BigInt? maxPriorityFeePerGas,
  required BigInt? gasLimit,
  required String chainId,
})
```

### Expected behavior

optional parameters need to be optional.

``` dart
 SendTransaction SendTransaction({
  required String fromAddress,
  String? toAddress,
  required BigInt weiValue,
  required String data,
  int? nonce,
  BigInt? gasPriceInWei,
  BigInt? maxFeePerGas,
  BigInt? maxPriorityFeePerGas,
  BigInt? gasLimit,
  required String chainId,
})
```

### Version

1.0.5

**Comment by bangtoven** [comment]
thanks for reporting the bug @moesaid 
we will take a look.
btw, feel free to open up a PR if you have good solutions. happy to review them.
thanks

**Comment by moesaid** [comment]
@bangtoven opened a quick PR https://github.com/coinbase/wallet-mobile-sdk/pull/188 for this bit

**Comment by bangtoven** [comment]
thank you @moesaid !

**Comment by bangtoven** [comment]
it's released. thanks for your contribution @moesaid !
https://pub.dev/packages/coinbase_wallet_sdk/versions/1.0.6
