### ISSUE TITLE
Feature Request: Flutter -- custom request - smart contract interaction

### ISSUE THREAD

**Issue by moesaid** [MobileWalletProtocol/wallet-mobile-sdk#190]
### Is your feature request related to a problem? Please describe.

any plan for a exposing a method for custom request? 
by passing `method name exist or custom` `custom prams`

is theres a way to interact with published smart contracts / diff assets other than the main currency of the network?

### Describe the solution you'd like

developing a smart contract can result of having a custom functions that need to be invoked , 
or dealing with an existing smart contract `e.g DAI on ethereum network`

if that's something we currently can do , is there's a write up i can take a look at?

**Comment by bangtoven** [comment]
hey @moesaid 
you can make request with custom actions with `eth_call` json rpc https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call
you may need to use other ethereum library to populate parameters for `eth_call` action.

i am marking this as question and closing it for now. come to our forum https://forums.coinbasecloud.dev/c/wallet/17 and discuss further there if needed. thanks.
