### ISSUE TITLE
Qestion: What is the meaning of "wsegue"?

### ISSUE THREAD

**Issue by chenkuangkuang** [MobileWalletProtocol/wallet-mobile-sdk#191]
### Describe the bug

I found a lot of "wsegue" in the sdk, including the hostURL and the mandatory suffix "callbackURL" in the source code, what is this for? Because this character will be displayed in the coinbase wallet connection screen.

### Steps

1. Take the RN project as an example, use "eth_requestAccounts" to start the connection

2. The coinbase app will pop up the connection screen, and the dapp package name will be followed by "wsegue"

![image](https://user-images.githubusercontent.com/20104135/219332963-baf05241-1cc4-4081-b0cc-32d5cc484513.png)

### Expected behavior

nothing

**Comment by bangtoven** [comment]
hey. we used to call this protocol WalletSegue, so url path on coinbase wallet to handle these messages is still using that.
you may use different path for your app.
if you have more questions, please come to our dev forum https://forums.coinbasecloud.dev/c/wallet

**Comment by chenkuangkuang** [comment]
@bangtoven What I'm wondering is that the coinbase sdk automatically adds "wsegue" to the callbackURL I set. According to the documentation, the callbackURL is only used to set the package name of the app, what is the purpose of the added suffix? Will the sdk request the URL I set and pass the parameters after the "request"?
