### ISSUE TITLE
Bug: SendTransaction does not work with other chain other than ethereum in using android sdk

### ISSUE THREAD

**Issue by amitsharma101** [MobileWalletProtocol/wallet-mobile-sdk#192]
### Describe the bug

When I try to do send transaction by changing the chain to 80001 (Polygon Mumbai), the wallet shows the error as "Something went wrong". I tried it with SwitchChain also.

### Steps

1. Go to ActionsManager in android sdk.
2. Chain chainId to 80001 in getSendTransaction and switchEthereumChain
3. Build and run the app and try"Make Request" in the example app
4. It will show "Something went wrong" in the coinbase app

### Expected behavior

The expected behavior is that it shows the prompt to show send a transaction as it does with the Ethereum chain but it does not

**Comment by bangtoven** [comment]
hey. you might need to put switchChain action first.
please visit our dev forum for more questions https://forums.coinbasecloud.dev/c/wallet

**Comment by amitsharma101** [comment]
> hey. you might need to put switchChain action first. please visit our dev forum for more questions https://forums.coinbasecloud.dev/c/wallet

I tried with switch chain first also as described in the bug.
