### ISSUE TITLE
Bug: SendTransaction does not work with other chain other than ethereum in using android sdk

### ISSUE THREAD

**Issue by amitsharma101** [MobileWalletProtocol/wallet-mobile-sdk#193]
### Describe the bug

When I try to do send transaction by changing the chain to 80001 (Polygon Mumbai), the wallet shows the error as "Something went wrong". I tried it with SwitchChain also. I raised this issue earlier but it was closed saying I need to use SwitchChain action first. I have tried that and it'smention in the description. It doesn't work with that as well.

### Steps

1. Go to ActionsManager in android sdk.
2. Chain chainId to 80001 in switchEthereumChain and getSendTransaction
3. Build and run the app and try"Make Request" in the example app
4. It will show "Something went wrong" in the coinbase wallet app

### Expected behavior

The expected behavior is that it shows the prompt to show send a transaction as it does with the Ethereum chain but it does not

**Comment by saisumit** [comment]
+1 to @amitsharma101, coinbase wallet is not working for us as well.

**Comment by saisumit** [comment]
Please mention in your docs that chain_id need to be passed in base10, we tried 137 which was failing with no particular error message. 89 worked!
