### ISSUE TITLE
Bug: "message" must be a nonempty string

### ISSUE THREAD

**Issue by chenkuangkuang** [MobileWalletProtocol/wallet-mobile-sdk#194]
### Describe the bug

"message" must be a nonempty string

### Steps

1.build android apk
2.run apk on my phone
3.click button and request "eth_requestAccounts"
4.The coinbase wallet app is opened and a connection message pops up, click connect.
5.Back to my app, catch the error '"message" must be a nonempty string'

### Expected behavior

wallet should return address

### Version

^1.0.4

### Additional info

Strangely enough, I was able to connect the real machine in the android development environment and it worked fine, only to find the error after packaging. So it was very difficult to debug.

The only special thing is that I replaced the mmkv used by the "WalletMobileSDKEVMProvider" with my own implementation of storage, as this dependency was not working properly due to various error reports and version inconsistencies.

![image](https://user-images.githubusercontent.com/20104135/220799896-81ec8142-7253-4151-81b5-58c4e9d0f240.png)

**Comment by chenkuangkuang** [comment]
I installed react-native-mmkv version 2.5.1 and dropped my own implementation of mmkv. development mode still works fine and the error persists after packaging

**Comment by vishnumad** [comment]
@chenkuangkuang Thanks for reporting. I was able to reproduce this issue for release builds when the `enableProguardInReleaseBuilds` option is set to true. We'll work on a fix for this. 

In the meantime, you can workaround this issue by adding the following to the `proguard-rules.pro` file in your Android directory.
```
-keepclassmembers class expo.modules.coinbasewalletsdkexpo.* {
    <fields>;
    <init>();
    <methods>;
}
```

Or you may disable proguard entirely by setting `enableProguardInReleaseBuilds` to false.
