### ISSUE TITLE
Bug: Using Package.swift error: 'CoinbaseWalletSDK' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by martinpristas** [MobileWalletProtocol/wallet-mobile-sdk#196]
### Describe the bug

Added Package to project and received a build error for file ExampleTest.swift

### Steps

1. Add package to your project
2. Run build
3. Error -> 'CoinbaseWalletSDK' is only available in iOS 13.0 or newer

SOLUTION is to add:
@available(iOS 13.0, *)
to ExampleTest.swift file

### Expected behavior

Buildable

### Version

recent

**Comment by cb-jake** [comment]
Thanks for reporting @martinpristas. @bangtoven will you be able to take a look at this?

**Comment by bangtoven** [comment]
@martinpristas thanks for reporting.
please try 1.0.5 https://github.com/coinbase/wallet-mobile-sdk/compare/1.0.4...1.0.5
