### ISSUE TITLE
Bug: can't build app for Android using Kotlin 1.8.0

### ISSUE THREAD

**Issue by nmalzieu** [MobileWalletProtocol/wallet-mobile-sdk#198]
### Describe the bug

The build phase fails with error ` The Android extensions ('kotlin-android-extensions') compiler plugin is no longer supported`

### Steps

1. Add the SDK to a react-native app
2. Try to build the app using Kotlin 1.8.0 (`kotlinVersion = "1.8.0"` in build.gradle)
3. See the following error:

```
[RUN_GRADLEW] > Task :coinbase-wallet-mobile-sdk:compileDebugKotlin FAILED
[RUN_GRADLEW] e: The Android extensions ('kotlin-android-extensions') compiler plugin is no longer supported. Please use kotlin parcelize and view binding. More information: https://goo.gle/kotlin-android-extensions-deprecation

```

4. Try it with Kotlin 1.7.0, it works!

### Expected behavior

It should work also with Kotlin 1.8.0. From the error it seems that Coinbase should move away from `kotlin-android-extensions`?

### Version

1.0.4

**Comment by cb-jake** [comment]
Thanks @nmalzieu for reporting. @vishnumad or @bangtoven are either of you able to take a look into this?

**Comment by iketw** [comment]
@vishnumad, thanks for all these fixes! When is this new version going to be out? Looking forward to testing it :)

**Comment by vishnumad** [comment]
@iketw 1.0.5 should be published now

**Comment by elkhoudiry** [comment]
I am having the same problem with the same setup 
Is there a solution for this
![image](https://github.com/coinbase/wallet-mobile-sdk/assets/16389332/d24837c7-6e5f-4bf4-910d-6736f4f01098)
