### ISSUE TITLE
Bug: Expo Go is not supported

### ISSUE THREAD

**Issue by iketw** [MobileWalletProtocol/wallet-mobile-sdk#206]
### Describe the bug

Using expo-modules breaks Expo Go support

### Steps

1. yarn create expo-app AwesomeProject
2. cd AwesomeProject
3. npx install-expo-modules@latest

Error: 
```
Uncaught Error [Error: ENOENT: no such file or directory, open '/AwesomeProject/android/build.gradle'] {
```

### Expected behavior

I'd like for this new package to work with Expo Go or at least to have a guide on how to make it work with `expo prebuild`.

### Version

1.0.4

**Comment by vishnumad** [comment]
At the moment Expo Go is not supported because this library has custom native dependencies. In Expo projects, you can use the [Expo Prebuild](https://docs.expo.dev/workflow/prebuild/) feature to generate the `android` and `ios` directories locally. 

```
npx expo prebuild
npx expo run:android
npx expo run:ios
```

**Comment by manan19** [comment]
@vishnumad It'd be great if there was direct support for Expo Go without needing to eject.

**Comment by Patel-Preet** [comment]
+1
