### ISSUE TITLE
Bug: SDK still requires minSdkVersion = 23

### ISSUE THREAD

**Issue by iketw** [MobileWalletProtocol/wallet-mobile-sdk#209]
### Describe the bug

The SDK is asking me to use minSdkVersion = 23 even though it has 21 defined in its gradle file

### Steps

1. Create a RN app with minSdkVersion = 21
2. Add the package: `@coinbase/wallet-mobile-sdk@^1.0.5`
3. Run `yarn android`

### Expected behavior

The app should work with minSdkVersion = 21 after this change if I'm not mistaken:

https://github.com/coinbase/wallet-mobile-sdk/pull/200/files#diff-00d8f1b43cac65c2c500b5e018dad9a17330112b8140378e3c4223e5505f232aR6.

Instead I get this error:

```
android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.coinbase:coinbase-wallet-sdk:1.0.4] transformed/jetified-coinbase-wallet-sdk-1.0.4/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 23,
```

### Version

1.0.5

### Desktop

- React native: 0.71.4 
- Coinbase npm package version: 1.0.5

**Comment by bangtoven** [comment]
hi @iketw 
the android library indeed needs min sdk version of 23 for some security features.
we found that the RN library didn't capture that, so we just fixed the config https://github.com/coinbase/wallet-mobile-sdk/pull/210
thanks for reporting the issue.

**Comment by iketw** [comment]
> hi @iketw 
> the android library indeed needs min sdk version of 23 for some security features.
> we found that the RN library didn't capture that, so we just fixed the config https://github.com/coinbase/wallet-mobile-sdk/pull/210
> thanks for reporting the issue.

Thanks for your answer, could elaborate on which security features?

**Comment by vishnumad** [comment]
@iketw We have calls to `android.security.keystore.KeyGenParameterSpec.Builder()` and `KeyguardManager.isDeviceSecure` in our [EncryptedStore](https://github.com/coinbase/wallet-mobile-sdk/blob/master/android/walletsdk/src/main/java/com/coinbase/android/nativesdk/key/EncryptedStore.kt#L133) that requires min sdk 23
