### ISSUE TITLE
Don't require UniversalLinks for ReactNative iOS to communicate back to the mobile app

### ISSUE THREAD

**Issue by iketw** [MobileWalletProtocol/wallet-mobile-sdk#213]
### Is your feature request related to a problem? Please describe.

Other wallets (e.g MetaMask, Rainbow) just redirect back to the app that opened the wallet without requiring to set up UniversalLinks. Setting up UniversalLinks is yet another friction point for developers who want to build mobile apps

### Describe the solution you'd like

I'd like for the wallet to redirect back to the app that triggered it without setting up Universal Links

**Comment by bangtoven** [comment]
Universal Link callback is required on MWP for security reasons. It's used to verify peers.
https://coinbase.github.io/wallet-mobile-sdk/docs/spec/verification
