### ISSUE TITLE
Bug: Cancelling the connection flow in React Native Android crashes the app

### ISSUE THREAD

**Issue by iketw** [MobileWalletProtocol/wallet-mobile-sdk#215]
### Describe the bug

Crash when cancelling the connection

### Steps

1. Try to connect to the coinbase wallet from a React Native Android app
2. Instead of selecting Allow, select Cancel
3. The RN app crashes. 

It seems the sdk is trying to look for the app in the Google Play Store?

```
SemWifiTransportLayerUtils: getApplicationCategory - IOException com.test15
03-28 23:16:13.891  1441  3294 W System.err: java.io.FileNotFoundException: https://play.google.com/store/apps/details?id=com.test15&hl=en
03-28 23:16:14.003 22497 22497 F DEBUG   : Cmdline: com.test15
03-28 23:16:14.003 22497 22497 F DEBUG   : pid: 22037, tid: 22120, name: mqt_js  >>> com.test15 <<<

```

### Expected behavior

I should be able to cancel the connection without having to publish my app to the app store first

### Version

1.0.5

**Comment by alaslyalasel** [comment]
Aslye

**Comment by iketw** [comment]
The issue was on our side. Closing since we found a work around to make it work.
