### ISSUE TITLE
Bug: React Native iOS stuck after calling provider.request

### ISSUE THREAD

**Issue by iketw** [MobileWalletProtocol/wallet-mobile-sdk#217]
### Describe the bug

After accepting connection in the wallet the call to `provider.request` doesn't resolve

### Steps

1. Create a React Native app for iOS
2. Setup Universal Links (it was such a pain to set this up, it would be nice if you could add a setup guide in your docs since you only point to the Apple docs but there's so much more to it to make `Linking.addEventListener` work :( )
3. Call:
```
await provider.request({
        method: "eth_requestAccounts",
        params: [],
      })
```
4. The wallet app opens up and shows the connection modal
5. Press `Allow`
6. The app re-opens up, the listener is triggered and `handleResponse(new URL(url));` is called but the call `await provider.request` is not resolved

### Expected behavior

The app re-opens after pressing on `Allow` and the call to `await provider.request` resolves with the connected account

### Version

1.0.5

**Comment by iketw** [comment]
@bangtoven could you please post the PR where this was fixed? I noticed this issue was closed without a note or PR

**Comment by iketw** [comment]
@bangtoven any updates on this?

**Comment by bangtoven** [comment]
hey. sorry for the late response.
we are currently working with thirdweb team.
