### ISSUE TITLE
Feature Request: Connect with Coinbase App

### ISSUE THREAD

**Issue by felipecamposfabel** [MobileWalletProtocol/wallet-mobile-sdk#221]
### Is your feature request related to a problem? Please describe.

Do you have any plans of adding support for connecting with the Coinbase App?

### Describe the solution you'd like

We have a website where, when used on mobile, the user is redirected to https://www.coinbase.com/connect-dapp and can choose how to connect. To keep it 1:1 it would be nice to have this feature on the React Native App as well.

**Comment by cb-jake** [comment]
Hey @felipecamposfabel, thanks for reaching out. 

This is currently on our roadmap. We don't have a specific timeline yet but can follow up when we do.
