### ISSUE TITLE
Bug: handleResponse with deeplink crashes the app on iOS

### ISSUE THREAD

**Issue by upacyxou** [MobileWalletProtocol/wallet-mobile-sdk#227]
### Describe the bug

When using the `handleResponse` function from `@coinbase/wallet-mobile-sdk` inside a React Native component with a `Linking` `url` listener in a `useEffect` hook, the app crashes upon opening a deeplink (e.g., `app://email?domain=domain&token=very-long-token`).

### Steps

1. Create a React Native component with a `Linking` `url` listener in a `useEffect` hook.
2. Add the handleResponse function from `@coinbase/wallet-mobile-sdk` as the listener.
3. Open the app's deeplink (e.g., `app://email?domain=domain&token=very-long-token`).
4. Notice that the app crashes.

### Expected behavior

The app should not crash when handling the deeplink with the `handleResponse` function.

### Version

1.0.6

### Additional info

<img width="498" alt="Screenshot 2023-06-15 at 18 32 40" src="https://github.com/coinbase/wallet-mobile-sdk/assets/57546893/6a24717e-410d-44b6-9e72-5458c9046068">

```
import { Linking } from 'react-native'
import { handleResponse } from '@coinbase/wallet-mobile-sdk'
import { useEffect } from 'react'

function App() {
  useEffect(() => {
    const sub = Linking.addEventListener('url', ({ url }) => {
      handleResponse(url)
    })
    return () => sub?.remove()
  }, [])

  return <></>
}

const WrapperApp = App

export default WrapperApp
```

**Comment by avr6ude** [comment]
Having the same problem.

**Comment by T-Damer** [comment]
Same for me, the app crashes on iOS if you open a deeplink with listener

**Comment by MixailE** [comment]
Year, iOS deeplinks...
Do you have any ideas on how to fix this?

**Comment by smyzin** [comment]
It's strange because I have the same issue on iOS, but Android is fine. Good workaround, but it's better to have a fix in the package

**Comment by bangtoven** [comment]
hey all. thanks for reporting the bug.
seems the code you shared looks pretty much the same as [our example](https://github.com/coinbase/wallet-mobile-sdk/blob/1cae82fbaefb9d3ea2223d3fddc884be4d71941a/react-native/client/example/App.js#L43), which doesn't crash btw.
can you share the error message you are getting?
![image](https://github.com/coinbase/wallet-mobile-sdk/assets/966662/f2202fa6-2e7f-41f3-9e0e-ff56242e3961)

**Comment by upacyxou** [comment]
> hey all. thanks for reporting the bug. seems the code you shared looks pretty much the same as [our example](https://github.com/coinbase/wallet-mobile-sdk/blob/1cae82fbaefb9d3ea2223d3fddc884be4d71941a/react-native/client/example/App.js#L43), which doesn't crash btw. can you share the error message you are getting? ![image](https://user-images.githubusercontent.com/966662/246205979-f2202fa6-2e7f-41f3-9e0e-ff56242e3961.png)

<img width="462" alt="Screenshot 2023-06-16 at 10 53 42" src="https://github.com/coinbase/wallet-mobile-sdk/assets/57546893/b9e41b18-1cea-4546-b7b7-6c7a5739ab4d">
<img width="624" alt="Screenshot 2023-06-16 at 10 53 49" src="https://github.com/coinbase/wallet-mobile-sdk/assets/57546893/88263d0a-2fc9-45ad-aab3-86acca194f27">

**Comment by bangtoven** [comment]
here you go:
https://coinbase.github.io/wallet-mobile-sdk/docs/client-sdk/rn-setup#configuration
