### ISSUE TITLE
com.coinbase.android.nativesdk.CoinbaseWalletSDKError$OpenWalletFailed: Could not open wallet

### ISSUE THREAD

**Issue by Aqib159** [MobileWalletProtocol/wallet-mobile-sdk#238]
### Describe the bug
I am trying to open my Coinbase wallet. I follow offical documentation of coinbase. First create an object for CoinBaseSDK and  Passed requirement parameters but i still faced same issue is that " could not open wallet". Here is my Code. Please solve my issue 

### Steps

Dependency i used in gradle:

    implementation "com.coinbase:coinbase-wallet-sdk:1.0.3"

also add a query parameter according to documentation 
`I passed required parameters including my Applink as a Uri:`

 ```
lateinit var client : CoinbaseWalletSDK

 client = CoinbaseWalletSDK(
            appContext = requireContext(),
            domain = Uri.parse("https://elmonx.page.link"),
             openIntent = { intent -> launcher.launch(intent) }
 
         )
```

 

`Initiate the SDK using initiateHandShake of CoinBaseSDK:`

        val requestAccount = Web3JsonRPC.RequestAccounts().action()
        val handShakeActions = listOf(requestAccount)

        client.initiateHandshake(
            initialActions = handShakeActions
        ) { result: Result<List<ActionResult>>, account: Account? ->
            result.onSuccess { actionResults: List<ActionResult> ->
                Log.d("CheckResult", "onViewCreated: ")
            }
            result.onFailure { err ->
                Log.d("CheckResult", "onViewCreated:  Fail")
            }
        }

### Expected behavior

Please any one have knowledge about that kindly share your answer

### Version

1.0.3

### Desktop

Android OS

### Smartphone

All Android Devices

**Comment by vishnumad** [comment]
Do you have this query added to your `AndroidManifest.xml` file?
```xml
    <queries>
        <package android:name="org.toshi" />
    </queries>
```
[See example](https://github.com/coinbase/wallet-mobile-sdk/blob/6771a9c4fe5ecdc9b9e9a81cd1cacff6d3ab60f3/android/example/src/main/AndroidManifest.xml#L30)

**Comment by Aqib159** [comment]
> Do you have this query added to your `AndroidManifest.xml` file?
> 
> ```
>     <queries>
>         <package android:name="org.toshi" />
>     </queries>
> ```
> 
> [See example](https://github.com/coinbase/wallet-mobile-sdk/blob/6771a9c4fe5ecdc9b9e9a81cd1cacff6d3ab60f3/android/example/src/main/AndroidManifest.xml#L30)

I already added this query in my manifest file

**Comment by Aqib159** [comment]
@vishnumad I already added this query in my AndroidManifest

**Comment by elkhoudiry** [comment]
I am having the same problem even in the sample app, i cloned it and tried to connect but also getting the same failure
![2023-07-20_13-13](https://github.com/coinbase/wallet-mobile-sdk/assets/16389332/319164fc-a169-4d36-b9b0-7d0f06621c2f)

**Comment by vizzdev** [comment]
@elkhoudiry Bro i solved this  issue. you just install coinbase wallet app in your testing device and pass this url "https://wallet.coinbase.com/wsegue"

**Comment by Aqib159** [comment]
I solved this issue . Just Pass this Url  as doman Url "https://wallet.coinbase.com/wsegue" and install coinbase app "https://play.google.com/store/apps/details?id=org.toshi" in your testing device
