### ISSUE TITLE
Bug: Wallet.coinbaseRetail.isInstalled returns false

### ISSUE THREAD

**Issue by prokhorovxo** [MobileWalletProtocol/wallet-mobile-sdk#246]
### Describe the bug

Coinbase iOS app is installed, but Wallet.coinbaseRetail.isInstalled still returns false

### Steps

1. Install Coinbase iOS App from the AppStore – https://apps.apple.com/app/id886427730
2. Add CoinbaseWalletSDK via SPM and configure the package according to the documentation
3. Add `<string>coinbase+mwp</string>` to `<key>LSApplicationQueriesSchemes</key>`
4. Check `Wallet.coinbaseRetail.isInstalled` value

### Expected behavior

Wallet.coinbaseRetail returns true

### Version

1.0.4

### Smartphone

- Device: iPhone 12 Pro Max
- iOS: 16.5.1
- Coinbase iOS app version: 11.29.7

**Comment by bangtoven** [comment]
hey @prokhorovxo 
sorry for the late response, 
please try using `cbwallet` as query scheme and see how it goes

**Comment by prokhorovxo** [comment]
Hello @bangtoven, thank you for your response! I don't have any problems with Coinbase Wallet app and its scheme cbwallet. I've a problem with Coinbase app and its scheme coinbase+mwp.

**Comment by bangtoven** [comment]
ah, gotcha. i don't think the retail coinbase app has this support yet.

**Comment by prokhorovxo** [comment]
@bangtoven are there plans to add sdk support to the retail app?

So also I think we can close this issue 🤷‍♂️
