### ISSUE TITLE
Bug: Latest version on IOS can't be connected

### ISSUE THREAD

**Issue by TheAmjadKhan** [MobileWalletProtocol/wallet-mobile-sdk#257]
### Describe the bug

After updating Coinbase wallet on IOS to latest version it's not showing connect popup

### Steps

1. update Coinbase wallet app on IOS
2. try to connect

### Expected behavior

should show connect screen 

### Version

1.0.6 on Flutter

### Desktop

IOS

### Smartphone

IOS

**Comment by vishnumad** [comment]
What value are you passing into the `configure` function for the host url?
<img width="469" alt="image" src="https://github.com/coinbase/wallet-mobile-sdk/assets/3137711/a7ee7949-eaf0-47bb-b056-4b70e100e8a9">

**Comment by TheAmjadKhan** [comment]
@vishnumad  I have been using this configuration from last 1 month and it was working fine until today when I updated to latest version on IOS 
```
 await CoinbaseWalletSDK.shared.configure(
        Configuration(
          ios: IOSConfiguration(
            host: Uri.parse('cbwallet://wsegue'),
            callback: Uri.parse('https://.link.sendcrypto.com/'),
          ),
          android: AndroidConfiguration(
            domain: Uri.parse('https://sendcrypto.com/'),
          ),
        ),
      );
```

**Comment by TheAmjadKhan** [comment]
@vishnumad  I updated configuration but it didn't worked, can you test latest version from app store if it work? 

```
       ios: IOSConfiguration(
            host: Uri.parse('https://wallet.coinbase.com/wsegue'),
            callback: Uri.parse('https://link.sendcrypto.com/'),
          ),
```

**Comment by bangtoven** [comment]
hi @AmjadKhan2k18 can you try the latest version `v28.64` which we released the fix on? thanks.

**Comment by TheAmjadKhan** [comment]
@bangtoven  yes it worked Thanks
