### ISSUE TITLE
Bug: React Native Example App iOS Fails to build

### ISSUE THREAD

**Issue by farukparhat** [MobileWalletProtocol/wallet-mobile-sdk#63]
### Describe the bug

Trying to build the iOS example app in react-native failes

### Steps

```
yarn install
cd ./react-native
yarn install
cd ./example
yarn install
cd ./ios
pod install
cd ..
yarn ios
```

Build fails with:
```
Node found at: /Users/farukparhat/.nvm/versions/node/v16.13.2/bin/node


2022-09-11 23:34:25.725 xcodebuild[28404:427100] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-09-11 23:34:25.725 xcodebuild[28404:427100] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal arm64 /Users/farukparhat/Workspace/dynamic/sandbox/wallet-mobile-sdk/react-native/example/node_modules/@coinbase/wallet-mobile-sdk/ios/CoinbaseWalletSDKModule.swift (in target 'CoinbaseWalletSDKExpo' from project 'Pods')
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'CoinbaseWalletSDKExpo' from project 'Pods')
(2 failures)
```

Using node16

### Expected behavior

- iOS build should pass and run on simulator.
- Trying to build on xCode result sin the below error when using xCode 14
![image](https://user-images.githubusercontent.com/2405774/189569402-d7126f7f-19a4-4640-81ae-f8d67cf956db.png)

**Comment by farukparhat** [comment]
I tried node v14 and received the following errors for `yarn ios`

```
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-example/Pods-example-frameworks-Debug-output-files.xcfilelist' (in target 'example' from project 'example')
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-example/Pods-example-resources-Debug-output-files.xcfilelist' (in target 'example' from project 'example')
error: Unable to load contents of file list: '/Target Support Files/Pods-example/Pods-example-frameworks-Debug-input-files.xcfilelist' (in target 'example' from project 'example')
error: Unable to load contents of file list: '/Target Support Files/Pods-example/Pods-example-resources-Debug-input-files.xcfilelist' (in target 'example' from project 'example')
error: Unable to load contents of file list: '/Target Support Files/Pods-example/Pods-example-frameworks-Debug-output-files.xcfilelist' (in target 'example' from project 'example')
error: Unable to load contents of file list: '/Target Support Files/Pods-example/Pods-example-resources-Debug-output-files.xcfilelist' (in target 'example' from project 'example')
```

**Comment by kukiz999** [comment]
> ### Describe the bug
> 
> Trying to build the iOS example app in react-native failes
> 
> ### Steps
> 
> ```
> yarn install
> cd ./react-native
> yarn install
> cd ./example
> yarn install
> cd ./ios
> pod install
> cd ..
> yarn ios
> ```
> 
> Build fails with:
> ```
> Node found at: /Users/farukparhat/.nvm/versions/node/v16.13.2/bin/node
> 
> 
> 2022-09-11 23:34:25.725 xcodebuild[28404:427100] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
> 2022-09-11 23:34:25.725 xcodebuild[28404:427100] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         CompileSwift normal arm64 /Users/farukparhat/Workspace/dynamic/sandbox/wallet-mobile-sdk/react-native/example/node_modules/@coinbase/wallet-mobile-sdk/ios/CoinbaseWalletSDKModule.swift (in target 'CoinbaseWalletSDKExpo' from project 'Pods')
>         CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'CoinbaseWalletSDKExpo' from project 'Pods')
> (2 failures)
> ```
> 
> Using node16
> 
> ### Expected behavior
> 
> - iOS build should pass and run on simulator.
> - Trying to build on xCode result sin the below error when using xCode 14
> ![image](https://user-images.githubusercontent.com/2405774/189569402-d7126f7f-19a4-4640-81ae-f8d67cf956db.png)
> 
> 
> ### Version
> 
> _No response_
> 
> ### Additional info
> 
> _No response_
> 
> ### Desktop
> 
> _No response_
> 
> ### Smartphone
> 
> _No response_

**Comment by Varentinevincent** [comment]
ส่งจาก แอป Mail.ru สำหรับ iOS


วันจันทร์ที่ 12 กันยายน 2565 10 นาฬิกา 37 นาที +0700 จาก ***@***.***  ***@***.***>:

**Comment by vishnumad** [comment]
I was able to build with Xcode 13 with the following
```
cd react-native
yarn install

cd example
yarn install
cd ios
pod  install
cd ..
yarn ios
```

Will take a look and see what broke with Xcode 14

**Comment by bangtoven** [comment]
hey @farukparhat thanks for your patience. i believe this change https://github.com/coinbase/wallet-mobile-sdk/pull/97 fixed the issue with xcode14. please try the latest master and let us know.
